name: pysa

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  pysa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abishekvashok/pyre-check@actions
      - run: cat .pysa/sarif.json
      - name: Expose SARIF Results
        uses: actions/upload-artifact@v2
        with:
          name: SARIF Results
          path: .pysa/sarif.json
      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: .pysa/sarif.json
     
